/*
  Auto-generated by Spline
*/

import useSpline from '@splinetool/r3f-spline'
import { OrbitControls, OrthographicCamera } from '@react-three/drei'

export default function Spline({ ...props }) {
  const { nodes, materials } = useSpline('https://prod.spline.design/XYmHsKswcgbLQrQ0/scene.splinecode')
  return (
    <>
      <color attach="background" args={['#e7e7e7']} />
      <group {...props} dispose={null}>
        <scene name="Scene">
          <mesh
            name="bgComingSoon.jpg"
            geometry={nodes['bgComingSoon.jpg'].geometry}
            material={materials['bgComingSoon.jpg Material']}
            castShadow
            receiveShadow
            position={[-164.15, 85.06, 2244.26]}
            scale={0.7}
          />
          <mesh
            name="Text 2"
            geometry={nodes['Text 2'].geometry}
            material={materials['Text 2 Material']}
            castShadow
            receiveShadow
            position={[3.48, 500.23, 2826.8]}
            scale={3.38}
          />
          <directionalLight
            name="Light Main"
            castShadow
            intensity={1}
            shadow-mapSize-width={1024}
            shadow-mapSize-height={1024}
            shadow-camera-near={-10000}
            shadow-camera-far={100000}
            shadow-camera-left={-500}
            shadow-camera-right={500}
            shadow-camera-top={500}
            shadow-camera-bottom={-500}
            position={[-129.8, 169.47, 157.37]}
          />
          <directionalLight
            name="Key Light"
            castShadow
            intensity={0.2}
            shadow-mapSize-width={1024}
            shadow-mapSize-height={1024}
            shadow-camera-near={-10000}
            shadow-camera-far={100000}
            shadow-camera-left={-500}
            shadow-camera-right={500}
            shadow-camera-top={500}
            shadow-camera-bottom={-500}
            position={[138.73, 169.47, -75.64]}
          />
          <mesh
            name="Floor"
            geometry={nodes.Floor.geometry}
            material={materials['Floor Material']}
            castShadow
            receiveShadow
            rotation={[-Math.PI / 2, 0, 0]}
          />
           {/* <OrbitControls 
              scale={0.1}
              args={}
        />  */}
          <OrthographicCamera name="1" makeDefault={true} far={10000} near={-4000} />
          {/* <OrthographicCamera name="1" makeDefault={true}  /> */}
          <hemisphereLight name="Default Ambient Light" intensity={0.75} color="#eaeaea" />
        </scene>
      </group>
    </>
  )
}
